name: C++ CI with Qt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 20 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        dir: '${{ github.workspace }}/qt-installation/'
        modules: 'qtcharts'

    - name: Configure and Build
      run: |
        qmake blackjack-game.pro
        make

    - name: Run Tests
      run: make check
